"""adiciona cfm_validated_at em doctors

Revision ID: c461f302647d
Revises: 18d4b5be4c38
Create Date: 2026-08-18 16:15:42.941355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c461f302647d'
down_revision: Union[str, Sequence[str], None] = '18d4b5be4c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('cfm_validated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'cfm_validated_at')
    # ### end Alembic commands ###
